### ISSUE TITLE
Error when build image

### ISSUE THREAD

**Issue by evleite** [blacklabelops/jira#11]
Hi There, first of all I would like to thanks for this amazing job.

I did some modifications in order to attend my needs and when I try to build I got error on log file and cannot run the container:

I ran the ./scripts/build.sh from root directory, should I use other command?

After download JIRA software:
Unpacking JRE ...
Starting Installer ...
Feb 24, 2017 12:48:51 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Feb 24, 2017 12:48:51 PM java.util.prefs.FileSystemPreferences$2 run
INFO: Created system preferences directory in java.home.
The installation directory has been set to /opt/jira.
Extracting files ...
java.io.IOException: Cannot run program "/opt/jira/bin/setup_user.sh" (in directory "/opt/jira/."): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at com.install4j.runtime.installer.helper.launching.LaunchHelper.launchOtherwise(Unknown Source)
	at com.install4j.runtime.installer.helper.launching.LaunchHelper.launchApplication(Unknown Source)
	at com.install4j.runtime.beans.actions.misc.RunExecutableAction.execute(Unknown Source)
	at com.install4j.runtime.beans.actions.SystemInstallOrUninstallAction.install(Unknown Source)
	at com.install4j.runtime.installer.InstallerContextImpl.performActionInt(Unknown Source)
	at com.install4j.runtime.installer.ContextImpl.performAction(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.executeActions(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.executeActions(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.handleCommand(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.start(Unknown Source)
	at com.install4j.runtime.installer.Installer.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.launcher.Launcher.main(Unknown Source)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 18 more
In action "set jira user account name [Run script]" (screen "Installation"), property "Script":
java.lang.NullPointerException
	at I4jScript_Internal_385.eval(I4jScript_Internal_385.java:18)
	at I4jScript_Internal_385.evaluate(I4jScript_Internal_385.java:27)
	at com.install4j.runtime.installer.helper.Script.evaluate(Unknown Source)
	at com.install4j.runtime.installer.ContextImpl.runScript(Unknown Source)
	at com.install4j.runtime.installer.ContextImpl.runScript(Unknown Source)
	at com.install4j.runtime.beans.actions.control.RunScriptAction.execute(Unknown Source)
	at com.install4j.runtime.beans.actions.SystemInstallOrUninstallAction.install(Unknown Source)
	at com.install4j.runtime.installer.InstallerContextImpl.performActionInt(Unknown Source)
	at com.install4j.runtime.installer.ContextImpl.performAction(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.executeActions(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.executeActions(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.handleCommand(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.start(Unknown Source)
	at com.install4j.runtime.installer.Installer.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.launcher.Launcher.main(Unknown Source)
An error occurred:
com.install4j.api.beans.UndefinedVariableException: installer:jiraAccountName
Error log: /tmp/install4jError1372929459834865074.log
com.install4j.api.beans.UndefinedVariableException: installer:jiraAccountName
	at com.install4j.runtime.installer.InstallerVariables$InstallerReplacementCallback.handleError(Unknown Source)
	at com.install4j.runtime.installer.InstallerVariables$InstallerReplacementCallback.getReplacement(Unknown Source)
	at com.install4j.runtime.util.StringUtil.replaceVariable(Unknown Source)
	at com.install4j.runtime.installer.InstallerVariables.replaceVariables(Unknown Source)
	at com.install4j.runtime.installer.InstallerVariables.replaceVariables(Unknown Source)
	at com.install4j.runtime.installer.InstallerVariables.replaceVariables(Unknown Source)
	at com.install4j.api.beans.AbstractBean.replaceVariables(Unknown Source)
	at com.install4j.runtime.beans.actions.text.ModifyTextFileAction.getReplaceValue(Unknown Source)
	at com.install4j.runtime.beans.actions.text.ModifyTextFileAction.modifyFile(Unknown Source)
	at com.install4j.runtime.beans.actions.files.AbstractModifyFileAction.executeForSingleFile(Unknown Source)
	at com.install4j.runtime.beans.actions.files.AbstractModifyFileAction.executeForMultipleFiles(Unknown Source)
	at com.install4j.runtime.beans.actions.files.AbstractModifyMultipleFilesAction.execute(Unknown Source)
	at com.install4j.runtime.beans.actions.SystemInstallOrUninstallAction.install(Unknown Source)
	at com.install4j.runtime.installer.InstallerContextImpl.performActionInt(Unknown Source)
	at com.install4j.runtime.installer.ContextImpl.performAction(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.executeActions(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.executeActions(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.handleCommand(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.start(Unknown Source)
	at com.install4j.runtime.installer.Installer.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.launcher.Launcher.main(Unknown Source)
java.io.IOException: Cannot run program "/opt/jira/bin/setup_user.sh" (in directory "/opt/jira/."): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at com.install4j.runtime.installer.helper.launching.LaunchHelper.launchOtherwise(Unknown Source)
	at com.install4j.runtime.installer.helper.launching.LaunchHelper.launchApplication(Unknown Source)
	at com.install4j.runtime.beans.actions.misc.RunExecutableAction.execute(Unknown Source)
	at com.install4j.runtime.beans.actions.SystemInstallOrUninstallAction.install(Unknown Source)
	at com.install4j.runtime.installer.InstallerContextImpl.performActionInt(Unknown Source)
	at com.install4j.runtime.installer.ContextImpl.performAction(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.executeActions(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.executeActions(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.handleCommand(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.start(Unknown Source)
	at com.install4j.runtime.installer.Installer.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.launcher.Launcher.main(Unknown Source)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 18 more
Launching JIRA Software ...
Feb 24, 2017 12:49:27 PM com.atlassian.modzdetector.HashRegistry store
INFO: wrote 987 hashes to /opt/jira/install.reg

When I try to run the image:
[FATAL tini (7)] Executing child process '/usr/local/share/atlassian/docker-entrypoint.sh' failed: 'No such file or directory'

My my change was in the file docker-entrypoint.sh
I add this:
if [ -n "${JIRA_JSESSIONID_NAME}" ]; then
  xmlstarlet ed -P -S -L --insert "//Context/[not(@sessionCookieName)]" --type attr -n sessionCookieName --value "${JIRA_JSESSIONID_NAME}" ${JIRA_INSTALL}/conf/server.xml
fi

Because when I run JIRA and Confluence in the same machine I got problems related with JSESSIONID and drop user from each application.

Thanks in advance.

**Comment by blacklabelops** [comment]
Hello Eduardo! 

Nice feature! Why don't you open a pull request? I will gladly accept another option into my image.

**Comment by blacklabelops** [comment]
Script `./scripts/build.sh` runs fine in the current version. Can you please tell me the changes you did to the Dockerfile?

**Comment by evleite** [comment]
Yes I will open a pull request with this feature.

I did not, I only changed the docker-entrypoint.sh.

Any suggestions about what can it be?

Another suggestion is to allow postgres image to create more than one DB when we use in docker compose. I did some test and when I use it twice the last overwrite the first one configurations.

**Comment by blacklabelops** [comment]
Your change looks good and correct.

Make sure the project is running smoothly before your changes:

1. Make sure to use latest Docker.
2. Execute `docker pull blacklabelops/alpine:3.5` (Updating base image)
3. Do a clean repository checkout and execute `./scripts/build.sh` inside the repository directory. 

Note to postgres: This would be a nice feature. You would need to introduce enumerated environment variables e.g. 

~~~~
$ docker run --name postgres -d \
    -e 'POSTGRES_USER=jira' \
    -e 'POSTGRES_PASSWORD=jellyfish' \
    -e 'POSTGRES_DB1=jiradb' \
    -e 'POSTGRES_ENCODING1=UNICODE' \
    -e 'POSTGRES_COLLATE1=C' \
    -e 'POSTGRES_COLLATE_TYPE1=C' \
    -e 'POSTGRES_DB2=confluencedb' \
    -e 'POSTGRES_ENCODING2=UNICODE' \
    -e 'POSTGRES_COLLATE2=C' \
    -e 'POSTGRES_COLLATE_TYPE2=C' \
    -e 'POSTGRES_DB3=bitbucketdb' \
    -e 'POSTGRES_ENCODING3=UNICODE' \
    -e 'POSTGRES_COLLATE3=C' \
    -e 'POSTGRES_COLLATE_TYPE3=C' \
    blacklabelops/postgres
~~~~

**Comment by evleite** [comment]
Great, thank you very much for your help.
I will create a new feature suggestions and will work on that.
